'use strict';

module.exports = {
    CATEGORY_INPUT: 'input',
    CATEGORY_EDITOR: 'editor',
    CATEGORY_LINK_OUTBOUND: 'link-outbound',
    CATEGORY_LINK_INTERNAL: 'link-inbound',
    ACTION_PICK_FILE: 'pick-file',
    ACTION_PICK_ICON: 'pick-icon',
    ACTION_ERROR: 'error',
    ACTION_BACK: 'back',
    ACTION_CHANGE_BASE_COLOR: 'change-base-color',
    ACTION_CHANGE_ICON_COLOR: 'change-icon-color',
    ACTION_CHANGE_SHADOW_LENGTH: 'change-shadow-length',
    ACTION_CHANGE_SHADOW_INTENSITY: 'change-shadow-intensity',
    ACTION_CHANGE_SHADOW_FADING: 'change-shadow-fading',
    ACTION_CHANGE_ICON_SIZE: 'change-icon-size',
    ACTION_CHANGE_CENTER_ICON: 'change-center-icon',
    ACTION_CHANGE_BASE_SHAPE: 'change-base-shape',
    ACTION_CHANGE_BANNER_VALUE: 'change-banner-value',
    ACTION_CHANGE_BANNER_BACKGROUND_COLOR: 'change-banner-background-color',
    ACTION_CHANGE_BANNER_TEXT_COLOR: 'change-banner-text-color',
    ACTION_DOWNLOAD: 'download',
    ACTION_CLICK: 'click',
};
